const profileImg = "assets/profile-img.png"; // person
const avOneImg = "assets/avatar-1.png"; // avatar 1
const avTwoImg = "assets/avatar-2.png"; // avatar 2
const avThreeImg = "assets/avatar-3.png"; // avatar 3
const avFourImg = "assets/avatar-4.png"; // avatar 4
const avFiveImg = "assets/avatar-5.png"; // avatar 5
const teamWorkImg = "assets/teamwork.svg"; // team work
const workToolImg = "assets/work-managemnt-icon.svg"; // work tool
const loginImg = "assets/login-img.svg"; // login
const forgotPassImg = "assets/forgot-password.svg"; // forgot password
